name: kwx-dev
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - black>=20.8b1
  - certifi>=2020.12.5
  - defusedxml>=0.7.1
  - gensim>=3.8.0
  - keras>=2.3.1
  - matplotlib>=3.3.2
  - nltk>=3.5
  - numpy>=1.19.2
  - packaging>=20.9
  - pandas>=1.2.1
  - pytest>=6.2.2
  - pytest-cov>=2.11.1
  - scikit-learn>=0.23.2
  - seaborn>=0.11.1
  - spacy>=2.3.5
  - tqdm>=4.56.0
  - wordcloud>=1.8.1
  - xlrd>=2.0.1
  - pip:
    - emoji>=1.2.0
    - googletrans==4.0.0rc1
    - ipython>=7.10.0
    - pyldavis>=3.2.0
    - sentence-transformers>=0.4.1.2
    - stopwordsiso>=0.6.1
    - tensorflow>=2.4.1
